# 移动
cmpp:
  client-id: "123456"
  address: "127.0.0.1:10086"
  segment: "^1(((3[56789]|47|5[012789]|65|7[28]|8[23478]|9[578])[0-9])|34[0-8]|705)[0-9]{7}$"
  max-conns: 4                      # 最大连接数
  mt-window-size: 16                # 接收窗口大小, 服务端分配, 用于限制未得到响应的消息的最大数量
  throughput: 1000                  # 最大吞吐, 单位tps, 服务端分配, 用于限制系统吞吐
  tick-duration: 1s                # 定时器调度间隔

# 联通
sgip:
  client-id: "123456"
  address: "127.0.0.1:10010"
  segment: "^1(((3[012]|4[56]|5[56]|6[67]|7[156]|8[56]|9[6])[0-9])|709)[0-9]{7}$"
  max-conns: 4
  mt-window-size: 16
  throughput: 1000
  tick-duration: 1s

# 电信
smgp:
  client-id: "12345678"
  address: "127.0.0.1:10000"
  segment: "^1(((33|49|53|62|7[347]|8[019]|9[139])[0-9])|349|700)[0-9]{7}$"
  max-conns: 4
  mt-window-size: 16
  throughput: 1000
  tick-duration: 1s