client-id: "123456"               # 即SourceAddr
shared-secret: "shared secret"    # 通讯密码
version: 48                       # 见CMPP协议，48表示3.0 即 0x30 = 0011 0000
need-report: 1                    # 是否需状态报告
sms-display-no: 95566             # 发送号码（后面可拼接子码）
service-id: myService             # 运营商分配的服务ID
default-msg-level: 9              # 默认短信优先级 （范围1-9）
fee-user-type: 2                  # 费用相关
fee-terminal-type:                # 费用相关
fee-terminal-id:                  # 费用相关
fee-type: 05                      # 费用相关
fee-code: free                    # 费用相关
link-id:                          # 点播业务相关
max-conns: 10                      # 最大连接数
mt-window-size: 512               # 接收窗口大小,服务端分配
mt-valid-duration: 2h        # 短信默认有效期，超过下面配置时长后，如果消息未发送，则不再发送
